In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm
import pickle
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,f1_score
import xgboost as xgb
from sklearn.ensemble import GradientBoostingClassifier

In [2]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_fa5a41007af545d79345a182de0d01bf = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='B98rjwlBDPLIBiyhrx_CkJYAK1UTP-2pfzH5wUDTRCga',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

body = client_fa5a41007af545d79345a182de0d01bf.get_object(Bucket='hackathoneducationloan-donotdelete-pr-liw4thfrl1b2mh',Key='Education_loan.xlsx')['Body']

data = pd.read_excel(body.read())
data.head()


phone     Education  Parent_Income CGPA  LoanAmount  Loan_Amount_Term  \
0  9456732610      Graduate           5000    A         129               360   
1  9456798085      Graduate           6000    D         128               360   
2  9456774514      Graduate          10000    A          66               360   
3  9456761419  Not Graduate          10000    S         120               360   
4  7694425773      Graduate          12500    A         141               360   

  Loan_Status  
0           Y  
1           N  
2           Y  
3           Y  
4           Y

In [3]:
data.isnull().any()

phone               False
Education           False
Parent_Income       False
CGPA                False
LoanAmount          False
Loan_Amount_Term    False
Loan_Status         False
dtype: bool

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   phone             40 non-null     int64 
 1   Education         40 non-null     object
 2   Parent_Income     40 non-null     int64 
 3   CGPA              40 non-null     object
 4   LoanAmount        40 non-null     int64 
 5   Loan_Amount_Term  40 non-null     int64 
 6   Loan_Status       40 non-null     object
dtypes: int64(4), object(3)
memory usage: 2.3+ KB


In [5]:
data=data.drop(['phone'],axis=1)
data

Education  Parent_Income CGPA  LoanAmount  Loan_Amount_Term Loan_Status
0       Graduate           5000    A         129               360           Y
1       Graduate           6000    D         128               360           N
2       Graduate          10000    A          66               360           Y
3   Not Graduate          10000    S         120               360           Y
4       Graduate          12500    A         141               360           Y
5       Graduate          14000    D         267               360           Y
6   Not Graduate          15000    A          95               360           Y
7       Graduate          18000    S         158               360           N
8       Graduate          19000    A         168               360           Y
9       Graduate          20000    D         349               360           N
10      Graduate          20000    A          70               360           Y
11      Graduate          22000    S         109               360           Y
12      Graduate          23400    A         200               360           Y
13      Graduate          24000    D         114               360           N
14      Graduate          24000    A          17               120           Y
15      Graduate          25000    S         125               360           Y
16  Not Graduate          25000    A         100               240           Y
17      Graduate          25000    D          76               360           N
18  Not Graduate          29000    A         133               360           N
19      Graduate          30000    S         115               200           Y
20  Not Graduate          30500    A         104               360           N
21      Graduate          32000    D         315               360           Y
22  Not Graduate          34000    A         116               360           N
23  Not Graduate          34000    S         112               360           N
24      Graduate          35000    A         151               360           N
25      Graduate          35000    D         191               360           Y
26      Graduate          39000    A         122               360           Y
27  Not Graduate          40000    S         110               360           Y
28  Not Graduate          42000    A          35               360           N
29      Graduate          43000    D         120               360           Y
30      Graduate          45000    A         201               360           N
31      Graduate          45000    S          74               360           N
32      Graduate          45000    A         106               360           N
33      Graduate          45000    D         114               360           Y
34      Graduate          46000    A         320               360           N
35      Graduate          47000    S         250               360           Y
36      Graduate          50000    A         100               200           N
37      Graduate          50500    D         144               360           Y
38      Graduate          55000    A         184               360           Y
39  Not Graduate          60000    S         110               360           Y

In [6]:
#label encoding
le = LabelEncoder()
data['Education'] = le.fit_transform(data['Education'])
data['Loan_Status'] = le.fit_transform(data['Loan_Status'])
data['CGPA'] = le.fit_transform(data['CGPA'])

In [7]:
data["CGPA"] = data["CGPA"].astype("string")

In [8]:
x1 = data.iloc[:,:5]
y1 = data.iloc[:,5:]

In [9]:
# divide data
x = data.iloc[:,:5].values
y = data.iloc[:,5:].values

In [10]:
x1

Education  Parent_Income CGPA  LoanAmount  Loan_Amount_Term
0           0           5000    0         129               360
1           0           6000    1         128               360
2           0          10000    0          66               360
3           1          10000    2         120               360
4           0          12500    0         141               360
5           0          14000    1         267               360
6           1          15000    0          95               360
7           0          18000    2         158               360
8           0          19000    0         168               360
9           0          20000    1         349               360
10          0          20000    0          70               360
11          0          22000    2         109               360
12          0          23400    0         200               360
13          0          24000    1         114               360
14          0          24000    0          17               120
15          0          25000    2         125               360
16          1          25000    0         100               240
17          0          25000    1          76               360
18          1          29000    0         133               360
19          0          30000    2         115               200
20          1          30500    0         104               360
21          0          32000    1         315               360
22          1          34000    0         116               360
23          1          34000    2         112               360
24          0          35000    0         151               360
25          0          35000    1         191               360
26          0          39000    0         122               360
27          1          40000    2         110               360
28          1          42000    0          35               360
29          0          43000    1         120               360
30          0          45000    0         201               360
31          0          45000    2          74               360
32          0          45000    0         106               360
33          0          45000    1         114               360
34          0          46000    0         320               360
35          0          47000    2         250               360
36          0          50000    0         100               200
37          0          50500    1         144               360
38          0          55000    0         184               360
39          1          60000    2         110               360

In [11]:
x

array([[0, 5000, '0', 129, 360],
       [0, 6000, '1', 128, 360],
       [0, 10000, '0', 66, 360],
       [1, 10000, '2', 120, 360],
       [0, 12500, '0', 141, 360],
       [0, 14000, '1', 267, 360],
       [1, 15000, '0', 95, 360],
       [0, 18000, '2', 158, 360],
       [0, 19000, '0', 168, 360],
       [0, 20000, '1', 349, 360],
       [0, 20000, '0', 70, 360],
       [0, 22000, '2', 109, 360],
       [0, 23400, '0', 200, 360],
       [0, 24000, '1', 114, 360],
       [0, 24000, '0', 17, 120],
       [0, 25000, '2', 125, 360],
       [1, 25000, '0', 100, 240],
       [0, 25000, '1', 76, 360],
       [1, 29000, '0', 133, 360],
       [0, 30000, '2', 115, 200],
       [1, 30500, '0', 104, 360],
       [0, 32000, '1', 315, 360],
       [1, 34000, '0', 116, 360],
       [1, 34000, '2', 112, 360],
       [0, 35000, '0', 151, 360],
       [0, 35000, '1', 191, 360],
       [0, 39000, '0', 122, 360],
       [1, 40000, '2', 110, 360],
       [1, 42000, '0', 35, 360],
       [0, 43000, '1',

In [12]:
#one hot encoding for Property Area and Dependents
one = OneHotEncoder()
cgpa = one.fit_transform(x[:,2:3]).toarray()

In [13]:
x1 = x1.drop(['CGPA'],axis=1)

In [14]:
x = np.delete(x,2,axis=1)

In [15]:
cgpas1 = pd.DataFrame(cgpa, columns = ['cgpa1','cgpa2','cgpa3'])

In [16]:
x1 = pd.concat([x1, cgpas1], axis=1)

In [17]:
x1

Education  Parent_Income  LoanAmount  Loan_Amount_Term  cgpa1  cgpa2  \
0           0           5000         129               360    1.0    0.0   
1           0           6000         128               360    0.0    1.0   
2           0          10000          66               360    1.0    0.0   
3           1          10000         120               360    0.0    0.0   
4           0          12500         141               360    1.0    0.0   
5           0          14000         267               360    0.0    1.0   
6           1          15000          95               360    1.0    0.0   
7           0          18000         158               360    0.0    0.0   
8           0          19000         168               360    1.0    0.0   
9           0          20000         349               360    0.0    1.0   
10          0          20000          70               360    1.0    0.0   
11          0          22000         109               360    0.0    0.0   
12          0          23400         200               360    1.0    0.0   
13          0          24000         114               360    0.0    1.0   
14          0          24000          17               120    1.0    0.0   
15          0          25000         125               360    0.0    0.0   
16          1          25000         100               240    1.0    0.0   
17          0          25000          76               360    0.0    1.0   
18          1          29000         133               360    1.0    0.0   
19          0          30000         115               200    0.0    0.0   
20          1          30500         104               360    1.0    0.0   
21          0          32000         315               360    0.0    1.0   
22          1          34000         116               360    1.0    0.0   
23          1          34000         112               360    0.0    0.0   
24          0          35000         151               360    1.0    0.0   
25          0          35000         191               360    0.0    1.0   
26          0          39000         122               360    1.0    0.0   
27          1          40000         110               360    0.0    0.0   
28          1          42000          35               360    1.0    0.0   
29          0          43000         120               360    0.0    1.0   
30          0          45000         201               360    1.0    0.0   
31          0          45000          74               360    0.0    0.0   
32          0          45000         106               360    1.0    0.0   
33          0          45000         114               360    0.0    1.0   
34          0          46000         320               360    1.0    0.0   
35          0          47000         250               360    0.0    0.0   
36          0          50000         100               200    1.0    0.0   
37          0          50500         144               360    0.0    1.0   
38          0          55000         184               360    1.0    0.0   
39          1          60000         110               360    0.0    0.0   

    cgpa3  
0     0.0  
1     0.0  
2     0.0  
3     1.0  
4     0.0  
5     0.0  
6     0.0  
7     1.0  
8     0.0  
9     0.0  
10    0.0  
11    1.0  
12    0.0  
13    0.0  
14    0.0  
15    1.0  
16    0.0  
17    0.0  
18    0.0  
19    1.0  
20    0.0  
21    0.0  
22    0.0  
23    1.0  
24    0.0  
25    0.0  
26    0.0  
27    1.0  
28    0.0  
29    0.0  
30    0.0  
31    1.0  
32    0.0  
33    0.0  
34    0.0  
35    1.0  
36    0.0  
37    0.0  
38    0.0  
39    1.0

In [18]:
x = np.concatenate((x,cgpas1),axis=1)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=0)

In [20]:
X_train,X_test,Y_train,Y_test = train_test_split(x1,y1,test_size=0.2,random_state=0)

In [21]:
#standard scaling because classification
#sc =  StandardScaler()
#x_train = sc.fit_transform(x_train)
#x_test = sc.transform(x_test)

In [22]:
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [23]:
X_train = pd.DataFrame(X_train, columns = ['Education','Parent_Income','LoanAmount','Loan_Amount_Term','cgpa1','cgpa2','cgpa3'])

In [24]:
def decisionTree(x_train,x_test,y_train,y_test):
    dtc = DecisionTreeClassifier(criterion='entropy',random_state=0)
    dtc.fit(x_train,y_train)
    y_pred_dtc = dtc.predict(x_test)
    print("Decision Tree Classifer\n")
    print("Confusion Matrix")
    print(confusion_matrix(y_test,y_pred_dtc))
    print("Classification Report")
    print(classification_report(y_test,y_pred_dtc))
    print("Accuracy: ")
    print(accuracy_score(y_test,y_pred_dtc))

In [25]:
#Random Forest Classifier
def randomForest(x_train,x_test,y_train,y_test):
    rfc=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    rfc.fit(x_train,y_train)
    y_pred_rfc = rfc.predict(x_test)
    print("Random Forest Classifer\n")
    print("Confusion Matrix")
    print(confusion_matrix(y_test,y_pred_rfc))
    print("Classification Report")
    print(classification_report(y_test,y_pred_rfc))
    print("Accuracy: ")
    print(accuracy_score(y_test,y_pred_rfc))

In [26]:
#KNeighbours Classifier
def KNN(x_train,x_test,y_train,y_test):
    knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski')
    knn.fit(x_train,y_train)
    y_pred_knn = knn.predict(x_test)
    print("KNeighbours Classifer\n")
    print("Confusion Matrix")
    print(confusion_matrix(y_test,y_pred_knn))
    print("Classification Report")
    print(classification_report(y_test,y_pred_knn))
    print("Accuracy: ")
    print(accuracy_score(y_test,y_pred_knn))

In [27]:
#Comparing the models
randomForest(x_train,x_test,y_train,y_test)

Random Forest Classifer

Confusion Matrix
[[2 0]
 [1 1]]
Classification Report
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.50      0.67         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4

Accuracy: 
0.75


/tmp/wsuser/ipykernel_164/1211179674.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(x_train,y_train)


In [28]:
decisionTree(x_train,x_test,y_train,y_test)

Decision Tree Classifer

Confusion Matrix
[[1 1]
 [1 1]]
Classification Report
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.50      0.50         2

    accuracy                           0.50         4
   macro avg       0.50      0.50      0.50         4
weighted avg       0.50      0.50      0.50         4

Accuracy: 
0.5


In [29]:
KNN(x_train,x_test,y_train,y_test)

KNeighbours Classifer

Confusion Matrix
[[1 1]
 [0 2]]
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.67      1.00      0.80         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4

Accuracy: 
0.75


/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [30]:
rf_clf = DecisionTreeClassifier(criterion='entropy',random_state=0)
rf_clf.fit(x_train, y_train)
y_pred = rf_clf.predict(x_train)

In [31]:
y_pred

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1])

In [32]:
y_train

array([[1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [33]:
print(accuracy_score(y_train,y_pred))

1.0


In [34]:
!pip install -U ibm-watson-machine-learning

     |████████████████████████████████| 1.8 MB 22.5 MB/s eta 0:00:01
  Attempting uninstall: ibm-watson-machine-learning
    Found existing installation: ibm-watson-machine-learning 1.0.232
    Uninstalling ibm-watson-machine-learning-1.0.232:
      Successfully uninstalled ibm-watson-machine-learning-1.0.232


In [35]:
from ibm_watson_machine_learning import APIClient
import json
import numpy as np

In [36]:
wml_credentials={
    "name": "hackathon_education_loan",
    "description": "hackathon_education_loan",
    "createdAt": "2022-09-07T17:06+0000",
    "apikey": "dUP-QDNhBbaSbd34czGKzVuCc_Nxp4HBkzT-X12vRnqJ",
    "url": "https://us-south.ml.cloud.ibm.com"
}

In [37]:
wml_client = APIClient(wml_credentials)
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  -----------------------  ------------------------
ID                                    NAME                     CREATED
54931202-cd2e-4cbe-a7c2-2866f668bc72  hackathon-home-loan      2022-09-07T09:43:53.583Z
3e34308a-4a80-4145-b009-7637e8e2963f  Loan Approval Predictor  2022-05-30T17:47:46.756Z
6d456318-2c91-4ca5-a443-b19563e1e7f7  Startup_Predictor        2022-05-22T11:49:45.681Z
------------------------------------  -----------------------  ------------------------


In [38]:
SPACE_ID = "3e34308a-4a80-4145-b009-7637e8e2963f"
wml_client.set.default_space(SPACE_ID)

'SUCCESS'

In [39]:
software_spec_uid = wml_client.software_specifications.get_uid_by_name("runtime-22.1-py3.9")
software_spec_uid

'12b83a17-24d8-5082-900f-0ab31fbfd3cb'

In [40]:
MODEL_NAME = 'hackathon education loan'
DEPLOYMENT_NAME = 'Sklearn Deployment'
BEST_MODEL = rf_clf

In [41]:
model_props = {
    wml_client.repository.ModelMetaNames.NAME: MODEL_NAME, 
    wml_client.repository.ModelMetaNames.TYPE: 'scikit-learn_1.0', 
    wml_client.repository.ModelMetaNames.SOFTWARE_SPEC_UID: software_spec_uid
}

In [42]:
model_details = wml_client.repository.store_model(model=BEST_MODEL, meta_props=model_props, training_data=None)

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/repository.py:1452: UserWarning: This method is deprecated, please use get_model_id()
  warn("This method is deprecated, please use get_model_id()")


In [43]:
model_id = wml_client.repository.get_model_uid(model_details)
model_id

This method is deprecated, please use get_model_id()


'9d1a03e1-d084-44b0-81c5-7e8fe7a5cc52'